# run: conda env create --file environment-dev.yml
name: lume-live-dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  - ipykernel
  - jupyterlab
  - pandas
  - pydantic
  - pyepics
  - scikit-image
  - toml
  - lume-impact
  - distgen
  - pip
  - pip:
    # TODO may not need this. Does it fix ImactTexe installation?
    - git+https://github.com/christophermayes/lume-impact
    - git+https://github.com/slaclab/lcls-live

  
